### ISSUE TITLE
RuboCop client: couldn't create connection to server

### ISSUE THREAD

**Issue by purnasrivatsa96** [rubocop/vscode-rubocop#9] opened 2023-09-08 23:34 UTC
I get this error on starting up vs code and opening a .rb file

**Comment by koic** [comment] 2023-10-13 05:40
RuboCop's built-in LSP is supported as of RuboCop 1.53+. Please update if you are using an older version of RuboCop.
#11 is a related issue.

If not, please provide details of the error.

**Comment by koic** [comment] 2023-10-17 02:40
I'll close this issue because it cannot be reproduced. But if the issue occurs even after upgrading RuboCop, please reopen with reproduction steps.

**Closed by koic** 2023-10-17 02:40 UTC
