### ISSUE TITLE
Changing the configuration file makes the extension angry

### ISSUE THREAD

**Issue by btrautmann** [rubocop/vscode-rubocop#23] opened 2023-12-14 17:36 UTC
I was switching from a non-official extension to this one, and at the same time I was adding a config file to my project. In doing so, I got a notification saying that the rubocop server crashed 5 times, and this was the output:

```console
[client] Starting language server: bundle exec rubocop --lsp
[server] RuboCop 1.59.0 language server initialized, PID 76175
[server] Configuration file changed; restart required
[Info  - 12:17:50 PM] Connection to server got closed. Server will restart.
[server] RuboCop 1.59.0 language server initialized, PID 77028
[server] Configuration file changed; restart required
[Info  - 12:17:54 PM] Connection to server got closed. Server will restart.
[server] RuboCop 1.59.0 language server initialized, PID 78104
[server] Configuration file changed; restart required
[Info  - 12:18:00 PM] Connection to server got closed. Server will restart.
[server] RuboCop 1.59.0 language server initialized, PID 78208
[server] Configuration file changed; restart required
[Info  - 12:18:07 PM] Connection to server got closed. Server will restart.
[server] RuboCop 1.59.0 language server initialized, PID 79328
[server] Configuration file changed; restart required
[Error - 12:18:10 PM] The RuboCop server crashed 5 times in the last 3 minutes. The server will not be restarted. See the output for more information.
```
This seems like an "expected" case that VSCode is treating as "unexpected", but figured it's worth calling out in case y'all can do something to make VSCode happier.

**Comment by koic** [comment] 2024-01-12 08:51
I'll close this issue because the cause may be the same as #22. Thank you for the feedback.

**Closed by koic** 2024-01-12 08:51 UTC
